pipeline {
  agent any
  stages {
    stage('Build') {
      agent {
        docker { image 'golang:latest' }
      }
      environment {
        GOPROXY = "goproxy.cn,direct"
      }
      steps {
        sh "go version"
      }
    }
  }
}
