pipeline {
  agent any
  stages {
    stage('Build') {
      agent {
        docker { image 'golang:latest' }
      }
      environment {
        GOPROXY = "goproxy.cn,direct"
        GOCACHE = "/tmp/.cache"
      }
      steps {
        sh "mkdir -p /tmp/.cache"
        sh "go build -o main"
        sh "echo hello world"
      }
    }
  }
}
